### PR TITLE
Upgrade to WildFly 10

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
[Don't merge yet]

**Comment by ppalaga** [comment]
2f02cdc brings an upgrade to srcdeps-maven-plugin and add a srcdep repository for Nest

**Comment by ppalaga** [comment]
06964bb brings yet another version of srcdeps-maven-plugin to fix yet another bug in it.

**Comment by ppalaga** [comment]
@jsanda could you please review and eventually merge?

Note that the last commit "Manage org.jboss.common:jboss-common-beans" is there to bring a replacement for `StringPropertyReplacer` that is not available in WF10. See e.g. https://github.com/ppalaga/hawkular-nest/commit/28095626292a0a978dcdf0140fd8ba9db6067732

**Comment by ppalaga** [comment]
Travis had some problems https://twitter.com/traviscistatus I hope the build will start and pass soon.

**Comment by jpkrohling** [comment]
@ppalaga , I see some references to a SHA for Keycloak. Is it for the wildfly-10 branch? If so, I'd first talk with the KC team to rebase it on top of the current master, as it seems it's a bit old and might affect Accounts.

**Comment by ppalaga** [comment]
@jpkrohling when I spoke with @mstruk last friday, he mentioned the need to rebase their WF10 branch too.

@mstruk, any estimate when we could count on the rebase of your WF10 branch on top of the recent KC master?

**Comment by ppalaga** [comment]
Looking at 1d3f707, it also adds the wf build plugins. Let me change the commit to add only the wf build plugins and take the KC srcdep sha1 out of it, so that parent 26 is not blocked by keycloak and so that @jsanda can work on the WF10 upgrade in Bus.

**Comment by mstruk** [comment]
@ppalaga I hope your build doesn't rely on our branches, since the only thing considered stable should be our tagged releases.

There is my [WF10 branch](https://github.com/mstruk/keycloak/commits/WF10) which is quite up-to-date with master. Then there is Keycloak [wildfly-10 branch](https://github.com/keycloak/keycloak/commits/wildfly-10) which currently lags behind.

We don't plan to merge wildfly-10 support into master until Wildfly 10.0.0.Final.

**Comment by jpkrohling** [comment]
Similarly, using 1.6.1.Final from my branch also makes the itest pass:

```
mvn clean install -Pitest -Dversion.org.keycloak=1.6.1.Final
```

Note, however, that this does _not_ mean that KC itself will work on WF 10. It just means that our code is not broken by this update :)

**Comment by ppalaga** [comment]
With ea9b00c , KC is back on 1.6.1.Final, keeping the srcdeps config for it there, so that we can eventually switch out components' builds to use KC master or whatever will work for us.

@mstruk  thanks for the info. To fulfill our WF10 objective, we will use whatever KC commit that will work for us and we hope to get a WF10 compatible release from you soon ;)

**Comment by jpkrohling** [comment]
LGTM, regarding KC.

**Comment by mstruk** [comment]
@ppalaga, what I wanted to say was that I regularly do force push on my WF10 so relying on specific commit hash won't end well :)

I'm also not sure we have a no-force-push policy for keycloak wildfly-10 branch. So if you rely on specific commit it's best that you fork the project, and rely on your fork.

**Comment by ppalaga** [comment]
@mstruk ah, thanks for the warning, but now you are warned as well what a damage you can cause to us!

**Pull request merged**
