### PR TITLE
Move gmavenplus-plugin executions to a dedicated profile so that it is not activ

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review? The idea is to disable `gmavenplus-plugin` in the default config so that the build runs a little bit faster for the most projects. The projects using groovy itest will have to add the `groovy.test` property to activate it.

```
<groovy.test>true</groovy.test>
```

**Comment by ppalaga** [comment]
7238108 adds a comment to the parent pom that informs about the purpose of the new `test.groovy` profile and unifies the names of the profile and the actiavtion property to `test.groovy` (one of them was `groovy.test` initially).

**Comment by jpkrohling** [comment]
Will it affect the groovy snippet we have in the pom.xml for Accounts, that generates UUIDs ?

**Comment by ppalaga** [comment]
> Will it affect the groovy snippet we have in the pom.xml for Accounts, that generates UUIDs ?

No, there should be no impact there. That execution of the plugin is fully independent of the one we are touching here.

**Comment by jpkrohling** [comment]
LGTM then.

**Comment by jpkrohling** [comment]
Actually, on a second thought... Why not do the reverse? Modules wanting this performance improvement can tweak their builds. This way, no change is required in modules that require this plugin.

**Comment by ppalaga** [comment]
> Why not do the reverse? Modules wanting this performance improvement can tweak their builds. This way, no change is required in modules that require this plugin.

Simply because there is just a handful of modules having groovy code. Doing the opposite would require much more work.

**Comment by jpkrohling** [comment]
Ok. In general, I think it's better to be "backwards compatible" and let performance-concerned parties to do the extra work to get this performance improvement. But in this case, it would make sense.

**Pull request merged**
