### PR TITLE
[HAWKULAR-1128] upgrade datastax driver

### PR DESCRIPTION
**Pull request by jsanda**

### CODE REVIEW

**Comment by pilhuhn** [comment]
@pgier Ok with this?
@jsanda what is the benefit of this?

**Comment by jsanda** [comment]
This was prior to the discussion and decision to move to Cassandra 3.09. I'll update the PR to upgrade to 3.0.4 which was recently released.

**Comment by pgier** [comment]
The upgrade is fine with me.
Do we also need an update of this?
`<version.org.apache.cassandra>3.5</version.org.apache.cassandra>`

**Comment by stefannegrea** [comment]
@pgier, we will need to update the C\* version too. But we will open another PR for that.

**Comment by stefannegrea** [comment]
Thank you @jsanda!

**Pull request merged**
