### PR TITLE
CSS license header should use slash star style

### PR DESCRIPTION
**Pull request by tsegismont**
I'm not sure double star even means something in CSS

### CODE REVIEW

**Comment by ppalaga** [comment]
I am basically not against this, but do you know how many files and in which repos would we have to reformat?

It would be good if @mtho11 and @ammendonca would ack this too. This change is about changing the license header style for css files from `/**` style that we use now to just `/*` style that is more common in the wild. We did the same thing for groovy files recently and we have that for Java since the beginning IIRC. License plugin defaults are unfortunate for these file types.

**Comment by tsegismont** [comment]
Le 14/08/2015 10:07, Peter Palaga a écrit :

> I am basically not against this, but do you know how many files and in
> which repos would we have to reformat?

Nope, no idea.

> It would be good if @mtho11 https://github.com/mtho11 and @ammendonca
> https://github.com/ammendonca would ack this too. This change is about
> changing the license header style for css files from |/*_| style that we
> use now to just |/_| style that is more common in the wild. We did the
> same thing for groovy files recently and we have that for Java since the
> beginning IIRC. License plugin defaults are unfortunate for these file
> types.

Note that it's only a matter of running `mvn license:format` when 
upgrading to the next parent version.

**Comment by ppalaga** [comment]
> it's only a matter of running `mvn license:format`

Have you tried that? I thought it would add a new `/*` header and leave the existing `/**` there. Maybe these two headers happen to be forward compatible because `/*` is a prefix of `/**`. Indeed, that would make the migration much easier.

**Comment by tsegismont** [comment]
Le 14/08/2015 10:46, Peter Palaga a écrit :

> Have you tried that?

Not with CSS but it worked for Groovy files.

**Comment by mtho11** [comment]
Our css files are actually generated from Less Pre-processor.

**Comment by ppalaga** [comment]
@mtho11 OK, let's see if we have any CSS files at all that will be impacted.

**Pull request merged**
