### PR TITLE
Manage maven-shade-plugin

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

**Comment by pilhuhn** [comment]
What is that for?

**Comment by ppalaga** [comment]
It is used in agent installer https://github.com/hawkular/hawkular-agent/blob/2b435be955949db7773da3367fd10b2605e14f6b/hawkular-wildfly-agent-installer/pom.xml#L77 @jmazzitelli should be able to explain what it is for

**Comment by jpkrohling** [comment]
That looks fine to me.

**Comment by jmazzitelli** [comment]
shade plugin was introduced to package the agent installer as a "runnable uber jar"

see jiri's commit when it was introduced - it works nicely :) commit 1e8d4f0fbb546f1e5673eea6bd5f7e0d7b5634a4

**Pull request merged**
