### PR TITLE
Cleanup README from superfluous information. 

### PR DESCRIPTION
**Pull request by stefannegrea**
This kind of documentation should be created at organization level and made available to contributors as part of the CLA.

### CODE REVIEW

**Comment by ppalaga** [comment]
Having contribution guide in README or in a separate file linked from README is quite usual. Having it per git repo is OK too as far as the processes differ among individual repos of the same org.

> should be created at organization level

I have no info that somebody would work on that. I vote for keeping the text here (thus rejecting the this PR) unless it can be replaced with a link leading to an organisation-wide contribution guide.

**Comment by stefannegrea** [comment]
There are only 5 people out of 7 billion possible that have commit access to this repo. Please talk with them individually. That part of the README puts a bad light on the project.

Let's keep the project clean.

**Comment by ppalaga** [comment]
> That part of the README puts a bad light on the project.

No, I'd say that it sheds good light, making all potential contributors equal rather than dividing them into admins that can do anything themselves and all others which have to be tortured by reviews.

I frankly did not know who all has push permissions on this repo till I have looked a couple of minutes ago.   I am not sure why I should speak to committers individually. I hope we all agree that this is an open project and all policies should be discussed in public? I mean it does not really matter who can push at the moment, the list of committers can change anytime.

I asked for comments about the contribution guide, when I was introducing it, on hawkular-dev ML. Nobody commented so far. Could we please move this discussion there?

**Comment by jmazzitelli** [comment]
Should this kind of thing be here, so its project-wide?

http://www.hawkular.org/docs/dev/development.html#_hack_the_code

**Comment by stefannegrea** [comment]
@ppalaga, everybody that has commit access to any repository, is equal peer. Let's not divide the community by some arbitrary conditions mentioned in a document or README. If you are trusted to get commit rights, then you have equal rights.

**Comment by stefannegrea** [comment]
The link that @jmazzitelli mentions is the perfect place for such documentation. And later we can make all new contributors acknowledge the document as part of the CLA. Let's not add unnecessary bureaucratic red tape on a project that does not have any public releases yet.

**Comment by ppalaga** [comment]
Indeed, http://www.hawkular.org/docs/dev/development.html#_hack_the_code seems to be a good place for some parts of the local contribution guide. But esp. the first part, speaking about impact of changes made in parent, is parent specific and should therefore stay here.

I am OK with moving the four eyes principle to hawkular wide docs. Which means I am OK with removing it from here as soon as it is there.

> @ppalaga, everybody that has commit access to any repository, is equal peer. Let's not divide the community by some arbitrary conditions mentioned in a document or README. If you are trusted to get commit rights, then you have equal rights.

I do not feel to be "dividing the community" in the README and I also do not understand the sense of the  other two sentences. Could you please be more specific? 

> And later we can make all new contributors acknowledge the document as part of the CLA.

What? You mean contributors should sign (or similar) the contribution guide? Why? Is it not enough to make it public, so that contributors know the expectations?

**Pull request merged**
