### PR TITLE
Upgrade to org.wildfly.build plugins 1.1.2.Final 

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

**Comment by jpkrohling** [comment]
I have no background information on the "XML format..." commit, so, I can't judge for that. The other commits are looking good to me.

**Comment by ppalaga** [comment]
> I have no background information on the "XML format..." commit

I doubt anybody except for me does :) The thing is that the code that we had in build tools [1] before today was recently accepted in xml-maven-plugin [2]. So we how use the same functionality but it is hosted somewhere else.

[1] https://github.com/hawkular/hawkular-build-tools/commit/4854421ad939db738ea4ac901d88470d74d71fe4#diff-4db3a10d5824a00aa1901f87c347ab41L105
[2] https://github.com/mojohaus/xml-maven-plugin/commit/e685d2ed7628164f44367c268247e879b5e4b63b#diff-aad20434f35dd1c23709f8103cfc56bcR22

**Comment by jpkrohling** [comment]
\o/

Sounds good to me, then.

**Pull request merged**
