### PR TITLE
HAWKULAR-176 Make maven to add git SHA1, branch and build time to

### PR DESCRIPTION
**Pull request by ppalaga**
manifest.mf

### CODE REVIEW

**Comment by pilhuhn** [comment]
@tsegismont I think you reviewed this?

**Comment by ppalaga** [comment]
@pilhuhn , Thomas reviewed, but I need to make sure that the change works well in all projects. I'll merge after that.

**Comment by tsegismont** [comment]
Yes I did, I'll copy what I said in the ML to Git Hub

2015-05-11 18:32 GMT+02:00 Peter Palaga notifications@github.com:

**Comment by tsegismont** [comment]
I suppose the last part of the PR is not related to the recent Kettle 
issues.
To me failing the build if local changes are present sounds like a good 
idea. But we must make sure that no plugin generates files outside of 
the "target" directory. Until recently the Swagger Maven plugin was 
writing doc files to the REST project base directory, for example.

If this is true then the PR looks good to me and it can be merged.

**Comment by stefannegrea** [comment]
Is this change going to affect all the artifacts created by individual projects?

**Comment by ppalaga** [comment]
@stefannegrea yes, this change will affect all artifacts (jars, wars and ears) created by individual projects as soon as the given project adopts the next hawkular parent version.

**Pull request merged**
