### PR TITLE
Add maven-ejb-plugin 2.5.1

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@metlos as I said, management of c\* moved to parent with newest 2.1.\* versions of c\* and driver. Could you please throw an eye on this?

**Comment by metlos** [comment]
eye thrown, no eyebrows raised, merged :)

**Comment by metlos** [comment]
oh, I can't merge :)

**Comment by ppalaga** [comment]
@metlos thanks for the effort!

**Pull request merged**
